/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarriereRouteImport } from './routes/carriere'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesRestaurationRouteImport } from './routes/services.restauration'
import { Route as ServicesLifestyleRouteImport } from './routes/services.lifestyle'
import { Route as ServicesBricolageRouteImport } from './routes/services.bricolage'
import { Route as ServicesBeautyRouteImport } from './routes/services.beauty'
import { Route as FranchiseSlugRouteImport } from './routes/franchise_.$slug'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as ServicesRestaurationSlugRouteImport } from './routes/services.restauration.$slug'
import { Route as ServicesLifestyleSlugRouteImport } from './routes/services.lifestyle.$slug'
import { Route as ServicesBricolageSlugRouteImport } from './routes/services.bricolage.$slug'
import { Route as ServicesBeautySlugRouteImport } from './routes/services.beauty.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriereRoute = CarriereRouteImport.update({
  id: '/carriere',
  path: '/carriere',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRestaurationRoute = ServicesRestaurationRouteImport.update({
  id: '/services/restauration',
  path: '/services/restauration',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLifestyleRoute = ServicesLifestyleRouteImport.update({
  id: '/services/lifestyle',
  path: '/services/lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBricolageRoute = ServicesBricolageRouteImport.update({
  id: '/services/bricolage',
  path: '/services/bricolage',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBeautyRoute = ServicesBeautyRouteImport.update({
  id: '/services/beauty',
  path: '/services/beauty',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseSlugRoute = FranchiseSlugRouteImport.update({
  id: '/franchise_/$slug',
  path: '/franchise/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ActualitesRoute,
} as any)
const ServicesRestaurationSlugRoute =
  ServicesRestaurationSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ServicesRestaurationRoute,
  } as any)
const ServicesLifestyleSlugRoute = ServicesLifestyleSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesLifestyleRoute,
} as any)
const ServicesBricolageSlugRoute = ServicesBricolageSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesBricolageRoute,
} as any)
const ServicesBeautySlugRoute = ServicesBeautySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesBeautyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/carriere': typeof CarriereRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/franchise/$slug': typeof FranchiseSlugRoute
  '/services/beauty': typeof ServicesBeautyRouteWithChildren
  '/services/bricolage': typeof ServicesBricolageRouteWithChildren
  '/services/lifestyle': typeof ServicesLifestyleRouteWithChildren
  '/services/restauration': typeof ServicesRestaurationRouteWithChildren
  '/services/beauty/$slug': typeof ServicesBeautySlugRoute
  '/services/bricolage/$slug': typeof ServicesBricolageSlugRoute
  '/services/lifestyle/$slug': typeof ServicesLifestyleSlugRoute
  '/services/restauration/$slug': typeof ServicesRestaurationSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/carriere': typeof CarriereRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/franchise/$slug': typeof FranchiseSlugRoute
  '/services/beauty': typeof ServicesBeautyRouteWithChildren
  '/services/bricolage': typeof ServicesBricolageRouteWithChildren
  '/services/lifestyle': typeof ServicesLifestyleRouteWithChildren
  '/services/restauration': typeof ServicesRestaurationRouteWithChildren
  '/services/beauty/$slug': typeof ServicesBeautySlugRoute
  '/services/bricolage/$slug': typeof ServicesBricolageSlugRoute
  '/services/lifestyle/$slug': typeof ServicesLifestyleSlugRoute
  '/services/restauration/$slug': typeof ServicesRestaurationSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/carriere': typeof CarriereRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/franchise_/$slug': typeof FranchiseSlugRoute
  '/services/beauty': typeof ServicesBeautyRouteWithChildren
  '/services/bricolage': typeof ServicesBricolageRouteWithChildren
  '/services/lifestyle': typeof ServicesLifestyleRouteWithChildren
  '/services/restauration': typeof ServicesRestaurationRouteWithChildren
  '/services/beauty/$slug': typeof ServicesBeautySlugRoute
  '/services/bricolage/$slug': typeof ServicesBricolageSlugRoute
  '/services/lifestyle/$slug': typeof ServicesLifestyleSlugRoute
  '/services/restauration/$slug': typeof ServicesRestaurationSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/carriere'
    | '/contact'
    | '/franchise'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/franchise/$slug'
    | '/services/beauty'
    | '/services/bricolage'
    | '/services/lifestyle'
    | '/services/restauration'
    | '/services/beauty/$slug'
    | '/services/bricolage/$slug'
    | '/services/lifestyle/$slug'
    | '/services/restauration/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/carriere'
    | '/contact'
    | '/franchise'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/franchise/$slug'
    | '/services/beauty'
    | '/services/bricolage'
    | '/services/lifestyle'
    | '/services/restauration'
    | '/services/beauty/$slug'
    | '/services/bricolage/$slug'
    | '/services/lifestyle/$slug'
    | '/services/restauration/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/carriere'
    | '/contact'
    | '/franchise'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/franchise_/$slug'
    | '/services/beauty'
    | '/services/bricolage'
    | '/services/lifestyle'
    | '/services/restauration'
    | '/services/beauty/$slug'
    | '/services/bricolage/$slug'
    | '/services/lifestyle/$slug'
    | '/services/restauration/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRouteWithChildren
  CarriereRoute: typeof CarriereRoute
  ContactRoute: typeof ContactRoute
  FranchiseRoute: typeof FranchiseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FranchiseSlugRoute: typeof FranchiseSlugRoute
  ServicesBeautyRoute: typeof ServicesBeautyRouteWithChildren
  ServicesBricolageRoute: typeof ServicesBricolageRouteWithChildren
  ServicesLifestyleRoute: typeof ServicesLifestyleRouteWithChildren
  ServicesRestaurationRoute: typeof ServicesRestaurationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriere': {
      id: '/carriere'
      path: '/carriere'
      fullPath: '/carriere'
      preLoaderRoute: typeof CarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/restauration': {
      id: '/services/restauration'
      path: '/services/restauration'
      fullPath: '/services/restauration'
      preLoaderRoute: typeof ServicesRestaurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lifestyle': {
      id: '/services/lifestyle'
      path: '/services/lifestyle'
      fullPath: '/services/lifestyle'
      preLoaderRoute: typeof ServicesLifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bricolage': {
      id: '/services/bricolage'
      path: '/services/bricolage'
      fullPath: '/services/bricolage'
      preLoaderRoute: typeof ServicesBricolageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/beauty': {
      id: '/services/beauty'
      path: '/services/beauty'
      fullPath: '/services/beauty'
      preLoaderRoute: typeof ServicesBeautyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise_/$slug': {
      id: '/franchise_/$slug'
      path: '/franchise/$slug'
      fullPath: '/franchise/$slug'
      preLoaderRoute: typeof FranchiseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/services/restauration/$slug': {
      id: '/services/restauration/$slug'
      path: '/$slug'
      fullPath: '/services/restauration/$slug'
      preLoaderRoute: typeof ServicesRestaurationSlugRouteImport
      parentRoute: typeof ServicesRestaurationRoute
    }
    '/services/lifestyle/$slug': {
      id: '/services/lifestyle/$slug'
      path: '/$slug'
      fullPath: '/services/lifestyle/$slug'
      preLoaderRoute: typeof ServicesLifestyleSlugRouteImport
      parentRoute: typeof ServicesLifestyleRoute
    }
    '/services/bricolage/$slug': {
      id: '/services/bricolage/$slug'
      path: '/$slug'
      fullPath: '/services/bricolage/$slug'
      preLoaderRoute: typeof ServicesBricolageSlugRouteImport
      parentRoute: typeof ServicesBricolageRoute
    }
    '/services/beauty/$slug': {
      id: '/services/beauty/$slug'
      path: '/$slug'
      fullPath: '/services/beauty/$slug'
      preLoaderRoute: typeof ServicesBeautySlugRouteImport
      parentRoute: typeof ServicesBeautyRoute
    }
  }
}

interface ActualitesRouteChildren {
  ActualitesSlugRoute: typeof ActualitesSlugRoute
}

const ActualitesRouteChildren: ActualitesRouteChildren = {
  ActualitesSlugRoute: ActualitesSlugRoute,
}

const ActualitesRouteWithChildren = ActualitesRoute._addFileChildren(
  ActualitesRouteChildren,
)

interface ServicesBeautyRouteChildren {
  ServicesBeautySlugRoute: typeof ServicesBeautySlugRoute
}

const ServicesBeautyRouteChildren: ServicesBeautyRouteChildren = {
  ServicesBeautySlugRoute: ServicesBeautySlugRoute,
}

const ServicesBeautyRouteWithChildren = ServicesBeautyRoute._addFileChildren(
  ServicesBeautyRouteChildren,
)

interface ServicesBricolageRouteChildren {
  ServicesBricolageSlugRoute: typeof ServicesBricolageSlugRoute
}

const ServicesBricolageRouteChildren: ServicesBricolageRouteChildren = {
  ServicesBricolageSlugRoute: ServicesBricolageSlugRoute,
}

const ServicesBricolageRouteWithChildren =
  ServicesBricolageRoute._addFileChildren(ServicesBricolageRouteChildren)

interface ServicesLifestyleRouteChildren {
  ServicesLifestyleSlugRoute: typeof ServicesLifestyleSlugRoute
}

const ServicesLifestyleRouteChildren: ServicesLifestyleRouteChildren = {
  ServicesLifestyleSlugRoute: ServicesLifestyleSlugRoute,
}

const ServicesLifestyleRouteWithChildren =
  ServicesLifestyleRoute._addFileChildren(ServicesLifestyleRouteChildren)

interface ServicesRestaurationRouteChildren {
  ServicesRestaurationSlugRoute: typeof ServicesRestaurationSlugRoute
}

const ServicesRestaurationRouteChildren: ServicesRestaurationRouteChildren = {
  ServicesRestaurationSlugRoute: ServicesRestaurationSlugRoute,
}

const ServicesRestaurationRouteWithChildren =
  ServicesRestaurationRoute._addFileChildren(ServicesRestaurationRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRouteWithChildren,
  CarriereRoute: CarriereRoute,
  ContactRoute: ContactRoute,
  FranchiseRoute: FranchiseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FranchiseSlugRoute: FranchiseSlugRoute,
  ServicesBeautyRoute: ServicesBeautyRouteWithChildren,
  ServicesBricolageRoute: ServicesBricolageRouteWithChildren,
  ServicesLifestyleRoute: ServicesLifestyleRouteWithChildren,
  ServicesRestaurationRoute: ServicesRestaurationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
